import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header";

const montserrat = localFont({
  src: "../fonts/Montserrat-Thin.woff",
  variable: "--font-montserrat-thin",
  weight: "100 900",
});
const openSans = localFont({
  src: "../fonts/OpenSans-Regular.woff",
  variable: "--font-open-sans-regular",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${montserrat.variable} ${openSans.variable} antialiased`}
      > <div>
        <Header />
        </div>
        <div className = "container mx-auto flex flex-col justify-center items-center min-h-screen px-12 pt-20 sm:pt-16">
        {children}
        </div>
        
      </body>
    </html>
  );
}
